resources:
- ./kubernetes-manifests/adservice.yaml
- ./kubernetes-manifests/cartservice.yaml
- ./kubernetes-manifests/checkoutservice.yaml
- ./kubernetes-manifests/currencyservice.yaml
- ./kubernetes-manifests/emailservice.yaml
- ./kubernetes-manifests/frontend.yaml
- ./kubernetes-manifests/loadgenerator.yaml
- ./kubernetes-manifests/paymentservice.yaml
- ./kubernetes-manifests/productcatalogservice.yaml
- ./kubernetes-manifests/recommendationservice.yaml
- ./kubernetes-manifests/redis.yaml
- ./kubernetes-manifests/shippingservice.yaml
images:
- name: adservice
  newName: registry.cn-shenzhen.aliyuncs.com/ymian/adservice:v1.0.0
- name: cartservice
  newName: registry.cn-shenzhen.aliyuncs.com/ymian/cartservice:v1.0.0
- name: checkoutservice
  newName: registry.cn-shenzhen.aliyuncs.com/ymian/checkoutservice:v1.0.0
- name: currencyservice
  newName: registry.cn-shenzhen.aliyuncs.com/ymian/currencyservice:v1.0.0
- name: emailservice
  newName: registry.cn-shenzhen.aliyuncs.com/ymian/emailservice:v1.0.0
- name: frontend
  newName: registry.cn-shenzhen.aliyuncs.com/ymian/frontend:v1.0.0
- name: loadgenerator
  newName: registry.cn-shenzhen.aliyuncs.com/ymian/loadgenerator:v1.0.0
- name: paymentservice
  newName: registry.cn-shenzhen.aliyuncs.com/ymian/paymentservice:v1.0.0
- name: productcatalogservice
  newName: registry.cn-shenzhen.aliyuncs.com/ymian/productcatalogservice:v1.0.0
- name: recommendationservice
  newName: registry.cn-shenzhen.aliyuncs.com/ymian/recommendationservice:v1.0.0
- name: shippingservice
  newName: registry.cn-shenzhen.aliyuncs.com/ymian/shippingservice:v1.0.0
patches:
- patch: |-
    - op: add
      path: /spec/selector/matchLabels/version
      value: v1
    - op: add
      path: /spec/template/metadata/labels/version
      value: v1
  target:
    kind: Deployment
    name: "productcatalogservice"
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: recommendationservice
    spec:
      template:
        spec:
          containers:
          - name: server
            env:
            - name: DISABLE_PROFILER
              value: "1"
            - name: DISABLE_TRACING
              value: "1"
            - name: DISABLE_DEBUGGER
              value: "1"
  target:
    kind: Deployment
    name: "recommendationservice"
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: emailservice
    spec:
      template:
        spec:
          containers:
          - name: server
            env:
            - name: DISABLE_PROFILER
              value: "1"
            - name: DISABLE_TRACING
              value: "1"
  target:
    kind: Deployment
    name: "emailservice"
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend
    spec:
      template:
        spec:
          containers:
          - name: server
            env:
            - name: ENV_PLATFORM
              value: "alibaba"
  target:
    kind: Deployment
    name: "frontend"
